# Generated by Django 5.2.11 on 2026-02-17 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_status_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Country Name')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Currency Name')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='Symbol')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_supplier', models.CharField(max_length=50, null=True, unique=True, verbose_name='Supplier ID')),
                ('legal_name', models.CharField(blank=True, max_length=150, verbose_name='Legal Name')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('tax_id', models.CharField(max_length=30, verbose_name='Tax ID')),
                ('state_province', models.CharField(max_length=60, verbose_name='State/Province')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Contact Name')),
                ('contact_role', models.CharField(max_length=150, verbose_name='Contact Role')),
                ('category', models.CharField(max_length=150, verbose_name='Category')),
                ('payment_terms', models.CharField(max_length=150, verbose_name='Payment Terms')),
                ('payment_method', models.CharField(max_length=150, verbose_name='Payment Method')),
                ('bank_account', models.CharField(max_length=150, verbose_name='Bank Account')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='suppliers.country', verbose_name='Country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='suppliers.currency', verbose_name='Currency')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
    ]
