# Generated by Django 5.2.11 on 2026-02-16 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_status_is_active'),
        ('suppliers', '0002_country_currency_alter_supplier_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Status'),
        ),
    ]
