# Generated by Django 5.2.11 on 2026-02-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_material',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Material ID'),
        ),
    ]
